name: bloggers
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - joblib=0.16.0
  - nltk=3.4.4
  - pandas=1.1.2
  - pip=20.2.4
  - python=3.7.8
  - scikit-learn=0.23.2
  - pip:
    - numpy==1.18.5
    - xgboost==1.2.0